version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_prueba_tecnica
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: escuela_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_prueba_tecnica
    ports:
      - "8082:8082"
    environment:
      
      DB_URI: jdbc:postgresql://db:5432/escuela_db 
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_DRIVER: org.postgresql.Driver
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend 
      dockerfile: Dockerfile
      args:
        
        - VITE_API_URL=http://localhost:8082/api 
    container_name: front_prueba_tecnica
    ports:
      - "80:80" # Se podrá ver la app web entrando simplemente a http://localhost
    depends_on:
      - backend

volumes:
  pgdata: