version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_prueba_tecnica
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: escuela_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: